version: "3.3"

services:
  frontend:
    image: frontend:v0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: e-com
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
      - ./forms:/app/forms
      - ./styles:/app/styles
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  data:
    name: frontend_volume
