version: "3.3"

services:
  frontend:
    image: frontend:v0.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"
