import { Inter } from "next/font/google";
import { Nav } from "@/components/Nav";
import { Banner } from "@/components/Banner";
import { Footer } from "@/components/Footer";
import { ContextProvider } from "@/context/contextProvider";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body className="bg-white">
        <ContextProvider>
          <Banner />
          <Nav />
          <main className="min-h-[77vh]">{children}</main>
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
